# https://embarkstudios.github.io/cargo-deny/index.html

[graph]
targets = [
    { triple = "x86_64-unknown-linux-gnu" },
    { triple = "aarch64-unknown-linux-gnu" },
    { triple = "x86_64-unknown-linux-musl" },
    { triple = "aarch64-apple-darwin" },
    { triple = "x86_64-apple-darwin" },
    { triple = "x86_64-pc-windows-msvc" },
    { triple = "wasm32-unknown-unknown" },
    { triple = "wasm32-wasi" },
    { triple = "aarch64-linux-android" },
    { triple = "aarch64-apple-ios" },
]
all-features = true
no-default-features = false

[output]
feature-depth = 1

[advisories]
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
yanked = "deny"
ignore = []
unmaintained = "workspace"

[licenses]
allow = [
    "0BSD",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "BSD-2-Clause-Patent",
    "BSL-1.0",
    "CC-BY-1.0",
    "CC-BY-2.0",
    "CC-BY-3.0",
    "CC-BY-4.0",
    "CC0-1.0",
    "CDLA-Permissive-1.0",
    "CDLA-Permissive-2.0",
    "FTL",
    "ISC",
    "JSON",
    "MIT",
    "MS-PL",
    "OpenSSL",
    "PostgreSQL",
    "SHL-0.5",
    "SHL-0.51",
    "TCP-wrappers",
    "Unicode-3.0",
    "Unicode-DFS-2016",
    "UPL-1.0",
    "W3C-20150513",
    "WTFPL",
    "Xnet",
    "Zlib",
]
confidence-threshold = 0.8
unused-allowed-license = "allow"

[licenses.private]
ignore = false
registries = []

[bans]
wildcards = "deny"
allow-wildcard-paths = true
multiple-versions = "warn"
highlight = "all"

[bans.workspace-dependencies]
duplicates = 'deny'
# TODO(template) you should provide an example with the lib usage
unused = 'deny'

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-git = []

[sources.allow-org]
github = ["NethermindEth"]
gitlab = []
bitbucket = []
